version: "3.9"

services:
  fastapi-app:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - ./src/backend/.env
    volumes:
      - ./src/backend/API:/app/API
      - ./src/backend/database:/app/database
      - ./src/backend/data_contract:/app/data_contract
      - ./src/backend/utils.py:/app/utils.py

  streamlit-frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: streamlit_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./src/frontend:/app
    depends_on:
      - fastapi-app
